version: '3'

services:

  backend:
    build: ./server
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - es-net
    volumes:
      - ./server:/server/accounts/
      - /server/server/accounts
    ports:
      - "8000:8000"


  # frontend:
  #   build: ./frontend
  #   depends_on:
  #     - backend
  #   command: ["npm", "start"]
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - /app/frontend/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

volumes:
  backend:
