version: '3'

services:

  backend:
    build: ./server
    environment:
      - AWS_ACCESS_KEY_ID=AKIA525LDBK2M3KUXK3R
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-east-1
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"

  # frontend:
  #   container_name: frontend
  #   build: ./Frontend
  #   volumes:
  #     - ./Frontend:/app
  #     - Naija_Ninjas_Frontend_NodeModules:/app/node_modules
  #   command: ["yarn", "start"]
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - backend

volumes:
  Naija_Ninjas_Frontend_NodeModules:
