# Generated by Django 3.1.2 on 2021-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
    ]
