# Generated by Django 4.0 on 2021-12-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="runnerprofile",
            old_name="review",
            new_name="reviews",
        ),
    ]
