# Generated by Django 4.0 on 2021-12-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='runnerprofile',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='user_views', to='accounts.IpModel'),
        ),
    ]
