# Generated by Django 4.0 on 2022-05-24 17:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerresume',
            name='accomplishment',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='attachment',
            field=models.FileField(blank=True, upload_to=accounts.models.upload_to_resume),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='career_profile',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='education',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='employment',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='projects',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='skills',
            field=models.JSONField(null=True),
        ),
    ]
