# Generated by Django 4.0 on 2022-01-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accountuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runnerresume",
            name="education",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="runnerresume",
            name="employment",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="runnerresume",
            name="projects",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="runnerresume",
            name="skills",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
