# Generated by Django 4.0 on 2021-12-26 04:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_runnerprofile_author_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
