# Generated by Django 3.1.2 on 2021-12-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('accounts', '0002_accountuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=55)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('Language', models.CharField(max_length=55)),
                ('location', models.CharField(max_length=55)),
                ('salary', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('local_goverment_zone', models.CharField(max_length=55)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='photo',
        ),
        migrations.CreateModel(
            name='Vidoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('video', models.FileField(blank=True, upload_to='documents/video/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_author', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('employment', models.TextField()),
                ('education', models.TextField()),
                ('projects', models.TextField()),
                ('profile_summary', models.CharField(max_length=255)),
                ('accomplishment', models.CharField(max_length=55)),
                ('career_profile', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('resume', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('runner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_profile', to='accounts.runnerprofile')),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='runnerprofile',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='users/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_author', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
