# Generated by Django 4.0 on 2022-05-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_runnerresume_accomplishment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runnerresume',
            name='profile',
        ),
    ]
