# Generated by Django 3.1.2 on 2021-12-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_runnerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='runnerprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='RunnerResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('employment', models.TextField()),
                ('education', models.TextField()),
                ('projects', models.TextField()),
                ('profile_summary', models.CharField(max_length=255)),
                ('accomplishment', models.CharField(max_length=55)),
                ('career_profile', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('resume', models.FileField(blank=True, upload_to='documents/%Y/%m/%d/')),
                ('runner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_profile', to='accounts.runnerprofile')),
            ],
        ),
    ]
