# Generated by Django 4.0 on 2022-05-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_runnerresume_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerresume',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.runnerprofile'),
        ),
    ]
