# Generated by Django 4.0 on 2022-06-03 20:51

import accounts.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_runnerresume_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='display',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(db_index=True),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, null=True)),
                ('description', ckeditor.fields.RichTextField(db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to='accounts.accountuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.upload_to)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_photos', to='accounts.projects')),
            ],
        ),
    ]
