# Generated by Django 4.0 on 2022-04-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_review_profile_runnerprofile_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='email_verified'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='phone_number_verified'),
        ),
    ]
