# Generated by Django 4.0 on 2022-06-05 22:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_display_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
