# Generated by Django 4.0 on 2022-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerresume',
            name='accomplishment',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='career_profile',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
