# Generated by Django 4.0 on 2022-06-07 01:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_service_description_alter_service_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerresume',
            name='accomplishment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='career_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='employment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runnerresume',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(db_index=True, null=True),
        ),
    ]
