# Generated by Django 4.0 on 2022-04-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_runnerresume_accomplishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='is_online'),
        ),
    ]
