# Generated by Django 4.0 on 2022-07-09 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_photo_image_alter_projectphoto_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='is_online',
        ),
        migrations.CreateModel(
            name='OnlineUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='online_status')),
                ('login_tracker', models.BooleanField(blank=True, default=False, verbose_name='login_tracker')),
                ('user_set_status', models.BooleanField(blank=True, default=False, verbose_name='is_online')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_online_status', to='accounts.accountuser')),
            ],
        ),
    ]
