# Generated by Django 4.0 on 2022-05-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountuser_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_index=True, max_length=250, null=True)),
                ('display', models.FileField(blank=True, upload_to='documents/user/service/photo/%Y/%m/%d/')),
                ('amount', models.CharField(max_length=250, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_author', to='accounts.accountuser')),
            ],
        ),
    ]
