# Generated by Django 4.0 on 2022-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accountuser_is_online_onlineuserstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='login_tracker',
            field=models.BooleanField(blank=True, default=False, verbose_name='login_tracker'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='online_status'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user_set_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_online'),
        ),
        migrations.DeleteModel(
            name='OnlineUserStatus',
        ),
    ]
