# Generated by Django 4.0 on 2022-05-03 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_runnerprofile_department_runnerprofile_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runnerprofile',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile_review', to='accounts.runnerprofile'),
        ),
    ]
