# Generated by Django 4.0 on 2022-07-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_accountuser_login_tracker_accountuser_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='login_tracker',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='user_set_status',
        ),
        migrations.AddField(
            model_name='runnerprofile',
            name='login_tracker',
            field=models.BooleanField(blank=True, default=False, verbose_name='login_tracker'),
        ),
        migrations.AddField(
            model_name='runnerprofile',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='online_status'),
        ),
        migrations.AddField(
            model_name='runnerprofile',
            name='user_set_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_online'),
        ),
    ]
