# Generated by Django 4.0 on 2022-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_runnerprofile_reviews_review_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_online'),
        ),
    ]
