# Generated by Django 4.0 on 2022-08-08 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_publicquotes_email_publicquotes_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerprofile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='profile_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
