# Generated by Django 4.0 on 2022-08-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_runnerprofile_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='on_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='on_time',
            field=models.BooleanField(default=False),
        ),
    ]
