# Generated by Django 4.0 on 2022-08-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_review_on_budget_review_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
