# Generated by Django 4.0 on 2022-08-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accountuser_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphoto',
            old_name='task',
            new_name='project',
        ),
    ]
