# Generated by Django 4.0 on 2022-08-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accountuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='password_reset_required',
            field=models.BooleanField(default=False, verbose_name='reset_password'),
        ),
    ]
