# Generated by Django 4.0 on 2022-08-31 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_accountuser_password_reset_required'),
        ('accounts', '0019_alter_review_profile'),
    ]

    operations = [
    ]
