# Generated by Django 4.0 on 2022-09-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_accountuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='task',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='task',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
