export const sectors = {
  "Home Improvement": [
    "Above Ground Pool Companies",
    "Air Quality Testing",
    "Appliance Install And Repair",
    "Appliance Repair",
    "Architects",
    "Artificial Turf Installation",
    "Asbestos Abatement Contractors",
    "Asphalt Pavers",
    "Sealcoating",
    "Basements",
    "Bathroom Remodeling",
    "Bed Bugs",
    "Masonry Contractors",
    "Cabinet Installation",
    "Kitchen Cabinet Painters",
    "Cabinet Refinishing",
    "Carpenters",
    "Carpet Cleaning",
    "Carpet Installation",
    "Carpet Removal Companies",
    "Carpet Repair",
    "Central Air Conditioning Installation",
    "Central Air Conditioning Repair",
    "Electrical Wiring And Panel Upgrade",
    "Circuit Breaker Companies",
    "Closet Builders",
    "Closets",
    "Commercial Carpet Cleaning",
    "Commercial Cleaning",
    "Concrete Contractors",
    "Concrete Removal",
    "Concrete Contractors",
    "Construction Estimating",
    "Countertop Installation",
    "Granite Countertop Repair",
    "Cabinet Makers",
    "Woodworkers",
    "Decks",
    "Decks",
    "Deck Repair",
    "Demolition Contractors",
    "Dishwasher Installation",
    "Doors",
    "Door Repair",
    "Drywall Repair",
    "Drywall Repair",
    "Duct Cleaning",
    "Roof Vent Installers",
    "Ducts And Vents",
    "Dumpster Rentals",
    "Electrical Repairs",
    "24 Hour Plumbers",
    "Engraving",
    "Epoxy Flooring",
    "Excavation",
    "Exterior Painting",
    "Attic Or Whole House Fan Installation",
    "Faux Finishes",
    "Fence Painters",
    "Fences",
    "Fences",
    "Finish Carpentry",
    "Fireplace Repair",
    "Fireplace Installation",
    "Fitness Equipment Assembly",
    "Floor Cleaning",
    "Hardwood Floor Installation",
    "Garage Floor Painters",
    "Stone Restoration And Polishing",
    "Subfloor Repair Contractors",
    "House Foundation Repair Companies",
    "Framing Contractors",
    "Lawn Care",
    "Furniture Assembly",
    "Furniture Delivery",
    "Movers",
    "Furniture Refinishing",
    "Furniture Repair",
    "Upholstery Repair",
    "Garage Addition",
    "Garage Doors",
    "Garage Door Repair",
    "Basement Cleaning Services",
    "Garbage Disposal Installation",
    "Garbage Disposal Repair",
    "Gardening",
    "Pipe Fitting Companies",
    "Gazebos",
    "Carpenters",
    "General Contractors",
    "Generators",
    "Generators",
    "Gutter Cleaners",
    "Gutters",
    "Gutter Repair",
    "Handyman",
    "Hardwood Floor Refinishing",
    "Furnace Installation",
    "Furnace Repair",
    "Holiday Lighting Installation",
    "Home Inspection",
    "Disability Retrofit",
    "Personal Organizers",
    "General Contractors",
    "Home Security",
    "Security Camera Install",
    "Home Staging",
    "Home Theater Installation",
    "Home Theater Repair",
    "Waterproofing",
    "Hot Tub Moving",
    "Hot Tub Cleaners",
    "Hot Tubs And Spas",
    "Hot Tubs And Spas",
    "House Cleaning",
    "House Sitting",
    "Pool Builders",
    "Insulation",
    "Interior Designers",
    "Interior Painting",
    "Junk Removal",
    "Kitchen Remodeling",
    "Brush Removal Services",
    "Landscape Grading Contractors",
    "Land Surveyors",
    "Lawn Mower Repairs",
    "Lawn Care",
    "Lighting",
    "Movers",
    "Locksmiths",
    "Long Distance Movers",
    "Masonry Contractors",
    "Metal Fabricators",
    "Mold Remediation",
    "Tree Services",
    "Mural Painter",
    "Custom Home Building",
    "Odor Removal",
    "Office Movers",
    "Landscaping",
    "Fly Control",
    "Exterminators",
    "Packing Services",
    "Paint Removal",
    "Patios",
    "Patios",
    "Exterminators",
    "Pest Inspection",
    "Piano Movers",
    "Picture Hanging",
    "Plastering",
    "Play Equipment",
    "Plumbing",
    "Plumbing Inspection",
    "Repiping Specialists",
    "Plumbing",
    "Pool Table Moving",
    "Pool Table Repairs",
    "Popcorn Removal",
    "Powder Coating",
    "Pressure Washing",
    "Property Management",
    "Radon Mitigation",
    "Stairs And Railings",
    "Real Estate Agents",
    "Appraisers",
    "Animal Removal Services",
    "Roof Cleaning",
    "Roof Inspection Services",
    "Roofing",
    "Roofing",
    "Remodeling Contractors",
    "Rug Cleaning",
    "Satellite Dish",
    "Window Screen Companies",
    "Septic Systems",
    "Septic Tank Cleaning",
    "Shower Installation",
    "Bathtub Refinishing",
    "Hedge Trimming Services",
    "Vinyl Siding Install",
    "Siding Contractors",
    "Vinyl Siding Repair",
    "Faucets And Fixtures",
    "Faucet Repairs",
    "Home Automation",
    "Snow Plow Services",
    "Sodding",
    "Solar Panel Cleaning",
    "Solar Panel Installation",
    "Soundproofing",
    "Irrigation System Companies",
    "Sprinkler Systems Repair",
    "Stairs And Railings",
    "Structural Engineers",
    "Stucco Contractors",
    "Stucco Repair",
    "Sump Pump Installation",
    "Swimming Pool Maintenance",
    "Swimming Pools",
    "Swimming Pool Removal",
    "Swimming Pool Repair",
    "Electrical Outlet Installation",
    "24 Hour Electricians",
    "Tv Wall Mount Install",
    "Tv Repair",
    "Termites",
    "Termite Inspection",
    "Thermostat Installation",
    "Tile",
    "Granite Marble And Slate Tile Repair",
    "Tile And Grout Cleaning",
    "Toilet Installation",
    "Plumbing",
    "Tree Movers",
    "Stump Grinding",
    "Tree Trimming",
    "Crown Moldings Installation",
    "Upholstery Cleaning",
    "Wallpaper Installation",
    "Wallpaper Removal",
    "Water Damage",
    "Water Features",
    "Water Features",
    "Water Heater Installation",
    "Water Heater Repair",
    "Water Softener Repair",
    "Water Softening",
    "Window Caulking Contractors",
    "Weeding",
    "Well Pump Installation",
    "Window Cleaners",
    "Window Installation",
    "Window Repair",
    "Residential Window Tinting",
    "Blind And Shade Install",
    "Window Air Conditioner Repair",
    "Wiring Installation",
  ],
  Wellness: [
    "Holistic Medicine",
    "Astrologers",
    "Facial",
    "Family Counselors",
    "Health Coaches",
    "Hypnosis",
    "Life Coach",
    "Marriage Counselors",
    "Massage",
    "Nutritionists",
    "Palm Readers",
    "Personal Trainers",
    "Physical Therapy",
    "Pilates",
    "Tai Chi Lessons",
    "Yoga",
    "Spiritual Counselors",
    "Tarot Card Readings",
    "Therapists",
  ],
  Pets: [
    "Animal Behavior",
    "Aquarium Service",
    "Cat Grooming",
    "Dog Day Care",
    "Pet Fence Installers",
    "Mobile Dog Grooming",
    "Dog Training",
    "Dog Walking",
    "Pet Boarding",
    "Pet Sitting",
  ],
  Business: [
    "Cad Design",
    "Accounting",
    "Personal Assistants",
    "Animators",
    "Business Consulting",
    "Tax Preparation",
    "Computer Repair",
    "Contract Attorneys",
    "Corporate Law Attorneys",
    "Translation",
    "Criminal Defense Attorneys",
    "Dui Attorney",
    "Data Recovery",
    "Elder Law Attorneys",
    "Divorce Lawyers",
    "Business Intelligence Consultants",
    "Coin Operated Machine Repair",
    "Civil Engineers",
    "Probate Attorneys",
    "Fitness Equipment Repair",
    "Family Law Attorneys",
    "Investigators",
    "Graphic Designers",
    "Illustrators",
    "Immigration Attorney",
    "Tax Preparation",
    "Patent Attorneys",
    "International Law Attorneys",
    "Employment Law Attorneys",
    "Paralegals",
    "Logo Design",
    "Marketing",
    "Mediators",
    "Freelance Web Designers",
    "Router Setup Install And Repair",
    "Notary Public",
    "Payroll Services",
    "Bankruptcy Attorneys",
    "Financial Planners",
    "Personal Injury Lawyers",
    "Phone Repair",
    "Presentation Design",
    "Copier Repair",
    "Private Investigators",
    "Process Servers",
    "Project Management Services",
    "Pr Consultants",
    "Real Estate Lawyers",
    "Recruiters",
    "Resume Writers And Editors",
    "Security Guards",
    "Social Media Marketing",
    "Software Developers",
    "Data Analysis Services",
    "Tax Attorneys",
    "Telemarketing Companies",
    "Traffic Attorneys",
    "Translation",
    "Virus Removal",
    "Web Design",
    "Web Hosting",
    "Wills Attorneys",
    "Writers",
  ],
  Events: [
    "Aerial Photography",
    "Tailors And Seamstresses",
    "Animal Show",
    "Recording Studio",
    "Balloon Decorators",
    "Balloon Twisting",
    "Grill Repair",
    "Bartenders",
    "Boudoir Photography",
    "Bouncy Houses",
    "Bridal Consultants",
    "Calligraphers",
    "Candy Buffet Planner",
    "Caricaturists",
    "Bus Charters",
    "Entertainers",
    "Clowns",
    "Comedians For Hire",
    "Commercial Photographers",
    "Costume Character Entertainers",
    "Custom Airbrushing",
    "Djs",
    "Burlesque Dancers",
    "Custom Embroidery",
    "Engagement Photographers",
    "Florists",
    "Waitstaff",
    "Party Planners",
    "Bouncer",
    "Face Painting",
    "Fishing Guides",
    "Mobile Food Trucks",
    "Concession Rentals",
    "Hair Stylists",
    "Headshots",
    "Henna Artists",
    "Impersonators",
    "Handmade Jewelry",
    "Karaoke Rental",
    "Limousines",
    "Emcees",
    "Magicians",
    "Motivational Speaker",
    "Bands For Hire",
    "Nature Photography",
    "Party Bus",
    "Custom Gift Baskets",
    "Pastry Chefs For Hire",
    "Personal Chefs",
    "Animal Photography",
    "Photo Booth Rentals",
    "Photo Restoration",
    "Art Services",
    "Portrait Photographers",
    "Quilt Makers",
    "Real Estate Photographers",
    "Scrapbook Makers",
    "Singing Telegrams",
    "Sommeliers",
    "Songwriters",
    "Sports Photography",
    "Tarot Card Readings",
    "Temporary Tattoo",
    "Travel Agency",
    "Valet Parking",
    "Entertainers",
    "Photo Booth Rentals",
    "Video Editors",
    "Video Production",
    "Streaming Services",
    "Video Transfer Services",
    "Fashion Stylists",
    "Wedding Cake",
    "Day Of Wedding Coordinators",
    "Wedding Dance Lessons",
    "Florists",
    "Wedding Officiants",
    "Wedding Planning",
    "Catering",
    "Event Decorators",
    "Hair Stylists",
    "Printing Services",
    "Makeup Artists",
    "Event Photographers",
    "Venue Management",
    "Videographers",
    "Wine Tasting Lessons",
  ],
  Lessons: [
    "Acting Lessons",
    "Arabic Lessons",
    "Audio Production Classes",
    "Banjo Lessons",
    "Baseball Instruction",
    "Basketball Training",
    "Bass Guitar Lessons",
    "Cpr Training",
    "Cello Lessons",
    "Chess Lessons",
    "College Application Assistance",
    "Excel Training",
    "Drawing Lessons",
    "Driving Lessons",
    "Drum Lessons",
    "English Lessons",
    "Flute Lessons",
    "French Lessons",
    "German Lessons",
    "Golf Lessons",
    "Graphic Design Classes",
    "Guitar Lessons",
    "Italian Lessons",
    "Japanese Lessons",
    "Korean Lessons",
    "Make Up Classes",
    "Mandarin Lessons",
    "Math Tutors",
    "Meditation Teachers",
    "Music Theory Lessons",
    "Painting Lessons",
    "Photography Lessons",
    "Piano Lessons For Kids",
    "Piano Tuners",
    "Portuguese Lessons",
    "Cooking Classes",
    "Dance Lessons",
    "Horseback Riding",
    "Self Defense",
    "Private Swim Lessons",
    "Tennis Lessons",
    "Public Speaking Training",
    "Reading And Writing Tutoring",
    "Reiki Lessons",
    "Saxophone Lessons",
    "Science Tutoring",
    "Sewing Instruction",
    "Sign Language Lessons",
    "Singing Lessons",
    "Soccer Training",
    "Social Studies Tutor",
    "Softball Training",
    "Spanish Lessons",
    "Test Prep",
    "Violin Lessons",
    "Voice Over Lessons",
    "Volleyball Training",
  ],
  Crafts: [
    "Custom Airbrushing",
    "Custom Embroidery",
    "Engraving",
    "Illustrators",
    "Art Services",
    "Powder Coating",
    "Scrapbook Makers",
    "Songwriters",
  ],
  "Design And Web": [
    "Animators",
    "Civil Engineers",
    "Graphic Designers",
    "Illustrators",
    "Logo Design",
    "Presentation Design",
    "Software Developers",
  ],
  Legal: [
    "Contract Attorneys",
    "Corporate Law Attorneys",
    "Translation",
    "Elder Law Attorneys",
    "Probate Attorneys",
    "Immigration Attorney",
    "Patent Attorneys",
    "International Law Attorneys",
    "Employment Law Attorneys",
    "Paralegals",
    "Mediators",
    "Personal Injury Lawyers",
    "Process Servers",
    "Radon Mitigation",
    "Real Estate Lawyers",
    "Tax Attorneys",
    "Traffic Attorneys",
    "Wills Attorneys",
  ],
  Personal: [
    "Astrologers",
    "Family Counselors",
    "Investigators",
    "House Sitting",
    "Life Coach",
    "Mediators",
    "Palm Readers",
    "Private Investigators",
    "Spiritual Counselors",
    "Tarot Card Readings",
    "Fashion Stylists",
  ],
  Photography: [
    "Aerial Photography",
    "Boudoir Photography",
    "Commercial Photographers",
    "Engagement Photographers",
    "Headshots",
    "Nature Photography",
    "Animal Photography",
    "Portrait Photographers",
    "Sports Photography",
    "Video Editors",
  ],
  "Repair And Technical Support": [
    [
      "Appliance Install And Repair",
      "Computer Repair",
      "Data Recovery",
      "Fitness Equipment Repair",
      "Router Setup Install And Repair",
      "Phone Repair",
      "Pool Table Repairs",
      "Copier Repair",
      "Writing, Translation, And Transcription",
      "Resume Writers And Editors",
      "Translation",
    ],
  ],
}
