# Generated by Django 4.0 on 2022-01-21 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="votes",
            field=models.ManyToManyField(
                blank=True, related_name="votes_forum", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
