# Generated by Django 4.0 on 2022-08-31 02:01

from django.db import migrations, models
import django_s3_storage.storage
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forum_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to='forum/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to=forum.models.upload_to),
        ),
    ]
