# Generated by Django 4.0 on 2022-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountuser_is_online'),
        ('forum', '0002_alter_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='forum_views', to='accounts.IpModel'),
        ),
    ]
