# Generated by Django 4.0 on 2022-08-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('Description', models.TextField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Postcode', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('local_government_zone', models.CharField(max_length=255)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketing.user_account')),
            ],
        ),
    ]
