# Generated by Django 4.0 on 2022-08-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Account',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
