# Generated by Django 4.0 on 2022-05-23 00:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=255)),
                ('minimum_salary', models.CharField(blank=True, db_index=True, max_length=255)),
                ('maximum_salary', models.CharField(blank=True, db_index=True, max_length=255)),
                ('region', models.CharField(blank=True, db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('department', models.TextField(db_index=True, null=True)),
                ('description', ckeditor.fields.RichTextField(db_index=True)),
                ('tags', models.CharField(blank=True, db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255)),
                ('attachment', models.FileField(blank=True, upload_to='task/documents/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post_status', models.CharField(choices=[('Open', 'Accepting offers'), ('Assigned', 'Task assigned to a pro'), ('Completed', 'Task completed!')], default='open', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='accounts.accountuser')),
                ('views', models.ManyToManyField(blank=True, related_name='task_views', to='accounts.IpModel')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TaskBidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bidder', models.ManyToManyField(blank=True, related_name='task_bidder', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
