# Generated by Django 4.0 on 2022-06-04 03:09

import ckeditor.fields
from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_experience_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sector',
        ),
        migrations.AddField(
            model_name='task',
            name='fixed_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='image',
            field=models.ImageField(blank=True, upload_to=task.models.upload_to),
        ),
    ]
