# Generated by Django 4.0 on 2022-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_sector_task_fixed_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
