# Generated by Django 4.0 on 2022-07-04 02:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_photo_image_alter_projectphoto_image_and_more'),
        ('task', '0004_task_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskbidder',
            old_name='confirmed',
            new_name='bid_approve_status',
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='runner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to='task/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_author', to='accounts.accountuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_task_owner', to='accounts.accountuser')),
            ],
        ),
    ]
