# Generated by Django 4.0 on 2022-07-04 13:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_photo_image_alter_projectphoto_image_and_more'),
        ('task', '0005_rename_confirmed_taskbidder_bid_approve_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='comment',
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='timeline',
            name='attachment',
            field=models.FileField(blank=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to='task/documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('attachment', models.FileField(blank=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to='task/documents/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_comment_author', to='accounts.accountuser')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_comment', to='task.timeline')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
