# Generated by Django 4.0 on 2022-07-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_timeline_comment_taskbidder_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timeline',
        ),
        migrations.AddField(
            model_name='timeline',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_comment', to='task.comment'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='timeline_status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('DELIVERED', 'DELIVERED'), ('REVIEW', 'REVIEW'), ('APPROVED', 'APPROVED')], default='STARTED', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='post_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=255),
        ),
    ]
