# Generated by Django 4.0 on 2022-07-16 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0007_remove_comment_timeline_timeline_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='task_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskbidder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned', to='task.task'),
        ),
        migrations.AlterField(
            model_name='taskbidder',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
