# Generated by Django 4.0 on 2022-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_bookmarks_taskbidder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='post_status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=255),
        ),
    ]
