# Generated by Django 4.0 on 2022-07-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_accountuser_login_tracker_and_more'),
        ('task', '0009_alter_task_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbidder',
            name='bidder',
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_bidder', to='accounts.accountuser'),
        ),
    ]
