# Generated by Django 4.0 on 2022-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_taskbidder_bidder_taskbidder_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbidder',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
