# Generated by Django 4.0 on 2022-07-25 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_publicquotes_email_publicquotes_phone'),
        ('task', '0011_alter_taskbidder_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskbidder',
            options={'ordering': ['-created', '-modified']},
        ),
        migrations.RemoveField(
            model_name='taskbidder',
            name='bidder',
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='bidder_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_profile_bidder', to='accounts.runnerprofile'),
        ),
    ]
