# Generated by Django 4.0 on 2022-07-31 02:33

from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_taskbidder_options_remove_taskbidder_bidder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='task_timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_timeline_comment', to='task.timeline'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to='tasktimeline/documents/%Y/%m/%d/'),
        ),
    ]
