# Generated by Django 4.0 on 2022-07-31 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_task_options_remove_timeline_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-updated', '-created')},
        ),
    ]
