# Generated by Django 4.0 on 2022-08-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskbidder',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
