# Generated by Django 4.0 on 2022-08-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_comment_contract_alter_taskbidder_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbidder',
            name='transaction_completed',
            field=models.BooleanField(default=False),
        ),
    ]
