# Generated by Django 4.0 on 2022-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_remove_task_bookmarks_taskbookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='timeline_status',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('CONTRACT', 'CONTRACT'), ('STARTED', 'STARTED'), ('PROGRESS', 'PROGRESS'), ('DELIVERED', 'DELIVERED'), ('CLIENT_REVIEW', 'CLIENT_REVIEW'), ('PRO_REVIEW', 'PRO_REVIEW'), ('APPROVED', 'APPROVED')], max_length=255, null=True),
        ),
    ]
