# Generated by Django 4.0 on 2022-08-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_review_on_budget_review_on_time'),
        ('task', '0018_remove_comment_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbidder',
            name='transaction_completed',
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='payment_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_author', to='accounts.accountuser'),
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='payment_submitted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='transaction_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
