# Generated by Django 4.0 on 2022-08-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_comment_delivery_date_comment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbidder',
            name='webhook_transaction_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
