# Generated by Django 4.0 on 2022-08-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_alter_taskbidder_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbidder',
            name='offer_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
