# Generated by Django 4.0 on 2022-08-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_taskbidder_offer_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='status',
            field=models.CharField(choices=[('CONTRACT', 'CONTRACT'), ('STARTED', 'STARTED'), ('PROGRESS', 'PROGRESS'), ('DELIVERED', 'DELIVERED'), ('CLIENT_REVIEW', 'CLIENT_REVIEW'), ('PRO_REVIEW', 'PRO_REVIEW'), ('APPROVED', 'APPROVED')], default='STARTED', max_length=255),
        ),
    ]
