# Generated by Django 4.0 on 2022-08-31 02:01

from django.db import migrations, models
import django_s3_storage.storage
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_timeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to='tasktimeline/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to=task.models.upload_to),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to='task/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='taskbidder',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to=task.models.upload_to),
        ),
    ]
