# Generated by Django 4.0 on 2022-08-31 14:57

from django.db import migrations, models
import django_s3_storage.storage
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_alter_comment_attachment_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskbidder',
            name='image',
        ),
        migrations.AddField(
            model_name='taskbidder',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to=task.models.upload_to),
        ),
    ]
