# Generated by Django 4.0 on 2022-09-03 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_photo_image_alter_projectphoto_image_and_more'),
        ('task', '0027_rename_offer_charge_taskbidder_total_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='accounts.accountuser'),
        ),
    ]
