# Generated by Django 4.0 on 2022-09-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0031_alter_task_post_status_biddersontask_task_bidders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='post_status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=255),
        ),
    ]
