# Generated by Django 4.0 on 2022-09-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0032_alter_task_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddersontask',
            name='bidder',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
