# Generated by Django 4.0 on 2022-09-08 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_accountuser_last_seen'),
        ('task', '0033_alter_biddersontask_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddersontask',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_profile_bidder', to='accounts.accountuser'),
        ),
    ]
