# Generated by Django 4.0 on 2022-09-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_accountuser_last_seen'),
        ('task', '0035_alter_taskbidder_total_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_author', to='accounts.accountuser'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='task_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_task_owner', to='accounts.accountuser'),
        ),
    ]
