# Generated by Django 4.0 on 2022-09-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_accountuser_last_seen'),
        ('task', '0036_alter_timeline_author_alter_timeline_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_comment_author', to='accounts.accountuser'),
        ),
        migrations.AlterField(
            model_name='taskbookmarks',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_bookmarks_author', to='accounts.accountuser'),
        ),
    ]
