# Generated by Django 4.0 on 2022-09-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0037_alter_comment_author_alter_taskbookmarks_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbidder',
            name='timeline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
