# Generated by Django 4.0 on 2023-01-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0038_taskbidder_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('CONTRACT', 'CONTRACT'), ('STARTED', 'STARTED'), ('PROGRESS', 'PROGRESS'), ('DELIVERED', 'DELIVERED'), ('CLIENT_REVIEW', 'CLIENT_REVIEW'), ('PRO_REVIEW', 'PRO_REVIEW'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='status',
            field=models.CharField(choices=[('CONTRACT', 'CONTRACT'), ('STARTED', 'STARTED'), ('PROGRESS', 'PROGRESS'), ('DELIVERED', 'DELIVERED'), ('CLIENT_REVIEW', 'CLIENT_REVIEW'), ('PRO_REVIEW', 'PRO_REVIEW'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='STARTED', max_length=255),
        ),
    ]
