# Generated by Django 4.0 on 2023-02-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_order_author_order_total_charge_and_more'),
        ('task', '0041_alter_taskbidder_bid_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
