# Generated by Django 4.0 on 2022-12-18 21:02

import bank.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_clientreview_task_review_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=bank.models.account_no_generator, editable=False, unique=True)),
                ('balance', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_owner', to='accounts.accountuser')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_balance', to='bank.currentbalance')),
            ],
        ),
    ]
