# Generated by Django 4.0 on 2023-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbalance',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
