# Generated by Django 4.0 on 2023-01-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_currentbalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbalance',
            name='invoice_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
