# Generated by Django 4.0 on 2023-01-22 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0040_alter_comment_status_alter_timeline_status'),
        ('bank', '0003_currentbalance_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbalance',
            name='payout_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_task_payment', to='task.taskbidder'),
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='transfer_to_available',
            field=models.BooleanField(default=False, verbose_name='transfer_to_available'),
        ),
    ]
