# Generated by Django 4.0 on 2023-01-22 21:26

import bank.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_clientreview_task_review_task'),
        ('bank', '0004_currentbalance_payout_date_currentbalance_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentbalance',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='currentbalance',
            name='balance',
        ),
        migrations.AddField(
            model_name='availablebalance',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_owner', to='accounts.accountuser'),
        ),
        migrations.AddField(
            model_name='availablebalance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='availablebalance',
            name='account_number',
            field=models.IntegerField(default=bank.models.account_no_generator, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='currentbalance',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_owner_invoice', to='accounts.accountuser'),
        ),
    ]
