# Generated by Django 4.0 on 2023-01-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_currentbalance_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablebalance',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
