# Generated by Django 4.0 on 2023-01-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_availablebalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbalance',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='invoice_approved'),
        ),
    ]
