# Generated by Django 4.0 on 2022-07-04 02:12

import chatserver.models
from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='zappa-wnf4dp8g2'), upload_to=chatserver.models.upload_to),
        ),
    ]
