# Generated by Django 4.0 on 2022-05-15 12:45

import chatserver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to=chatserver.models.upload_to),
        ),
    ]
