# Generated by Django 4.0 on 2022-08-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0003_alter_message_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='conversation',
            name='new_message_alert',
            field=models.BooleanField(blank=True, default=False, verbose_name='new_message_alert'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
