# Generated by Django 4.0 on 2022-09-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0005_alter_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('FILE', 'FILE'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('PICTURE', 'PICTURE')], default='FILE', max_length=255),
        ),
    ]
