# Generated by Django 4.0 on 2022-08-05 15:48

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=payment.models.key_generator, editable=False, max_length=6, unique=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('payment_date_time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('status', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('refrence', models.CharField(db_index=True, max_length=255)),
                ('logs', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
