# Generated by Django 4.0 on 2022-08-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_transactionlog_payment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='payment_date_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
