# Generated by Django 4.0 on 2022-08-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transactionlog_payment_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='refrence',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
