# Generated by Django 4.0 on 2022-08-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_review_on_budget_review_on_time'),
        ('payment', '0004_alter_transactionlog_refrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_payment_lof_field', to='accounts.accountuser'),
        ),
        migrations.CreateModel(
            name='ClientPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=255)),
                ('last4', models.CharField(max_length=255)),
                ('exp_month', models.CharField(max_length=255)),
                ('exp_year', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_payment_author', to='accounts.accountuser')),
            ],
        ),
    ]
