# Generated by Django 4.0 on 2022-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_transactionlog_author_clientpaymentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='author',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='author',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
