# Generated by Django 4.0 on 2022-08-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_clientpaymentinfo_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='refrence',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
