# Generated by Django 4.0 on 2022-08-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_transactionlog_refrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaymentinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
