# Generated by Django 4.0 on 2022-08-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_clientpaymentinfo_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientpaymentinfo',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
