# Generated by Django 4.0 on 2022-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_clientpaymentinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='card_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='country_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='exp_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='exp_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentinfo',
            name='last4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
