# Generated by Django 4.0 on 2023-02-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_runnerprofile_interest_runnerprofile_phone_number'),
        ('payment', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_author', to='accounts.accountuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_verified',
            field=models.BooleanField(default=False),
        ),
    ]
